#!/bin/bash

sleep 15

sudo apt-get update
sudo apt-get install -y python-pip
yes | sudo pip install awscli

mkdir ~/.aws

cat << EOF > ~/.aws/credentials
[default]
EOF

echo "aws_access_key_id = $ACCESS_KEY" >> ~/.aws/credentials
echo "aws_secret_access_key = $SECRET_KEY" >> ~/.aws/credentials

cat << EOF > ~/.aws/config
[default]
output = text
region = us-west-2
EOF

sudo mkdir -pv /root/.aws
sudo cp ~/.aws/* /root/.aws/
